<a href="https://colab.research.google.com/github/chaehchaeh/MajorAI-DL/blob/main/220900dl2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

파이토치 텐서 형태 변환:View함수

In [ ]:
#크기가 3*2*2인 파이토치 텐서 생성
x=torch.FloatTensor([[[1,2],
                      [3,4]],
                     [[5,6],
                      [7,8]],
                     [[9,10],
                      [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [ ]:
#View함수: 텐서 요소의 총 개수는 유지한 채 shape를 바꿀 수 있음
print(x.view(12))#요소를 가져오는 순서:사전식

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [ ]:
print(x.view(3,1,4))#요소를 가져오는 순서: 사전식 순서로 요소를 가져와 3x1x4인 텐서를 구성함

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [ ]:
#1활용하기: -1이 들어간 차원의 크기를 자동계산
print("0번 차원의 크기가 12로 자동계산")
print(x.view(-1))
print()
print("1번 차원의 크기가 4로 자동계산")
print(x.view(3,-1))
print()
print("0번 차원의 크기가 3으로 자동계산")
print(x.view(-1,1,4))

0번 차원의 크기가 12로 자동계산
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

1번 차원의 크기가 4로 자동계산
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

0번 차원의 크기가 3으로 자동계산
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [ ]:
#view함수의 변환값은 같은 메모리(저장공간)를 공유하고 있기 때문에 아래 코드에서 y가 바뀌면 x도 바뀜
y=x.view(3,4)
x.storage().data_ptr()==y.storage().data_ptr()

True

###view함수 사용시 만날 수 있는 에러 메시지
     RuntimeError:view size is not compatible with input tensor's size and stride
     (at least one dimension spans across two contiguous subspaces). Use.reshape(...)instead.
#### 해결방법1: contiguous함수 사용 후 view함수 호출
(주의:텐서의 주소가 변경될 수 있음)
#### 해결방법2: view함수 대신 reshape함수 이용(contiguous+view 효과)
(주의: 텐서의 주소가 변경될 수 있음)
 print(x.reshape(3,4))
 -->tensor([[1.,2.,3.,4.],
 [5.,6.,7.,8.],
 [9.,10.,11.,12.]])

# 2. 파이토치 텐서 형태 변환: sqeeze함수

In [ ]:
#크기가 1x2x2인 파이토치 텐서 생성
x=torch.FloatTensor([[[1,2],
                      [3,4]]])
print(x.size())

torch.Size([1, 2, 2])


In [ ]:
#squeeze함수: 크기가 1인 차원 없앨 수 있음
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [ ]:
#원하는 차원을 지정해서 없앨 수 있음
#단, 지정한 차원의 크기가 1이 아니면 없애지 못함
print(x.squeeze(0).size())
torch.Size([2,2])
print(x.squeeze(1).size())
torch.Size([1,2,2])

torch.Size([2, 2])
torch.Size([1, 2, 2])


torch.Size([1, 2, 2])

# 3. 파이토치 텐서 변환: unsqueeze함수

In [ ]:
#크기가 2x2인 파이토치 텐서 생성
x=torch.FloatTensor([[1,2],[3,4]])
print(x.size())

torch.Size([2, 2])


In [ ]:
#지정한 차원에 크기가 1인 차원을 추가
print(x.unsqueeze(1).size())
print(x.unsqueeze(-1).size())
print(x.unsqueeze(2).size())

torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
torch.Size([2, 2, 1])


In [ ]:
#참고: reshape 함수를 이용해서도 가능함
print(x.reshape(2,2,-1).size())

torch.Size([2, 2, 1])


# 4. 파이토치 텐서 자르기:인덱싱과 슬라이싱

In [ ]:
#크기가 3x2x2인 파이토치 텐서 생성
x=torch.FloatTensor([[[1,2],
                      [3,4]],
                     [[5,6],
                      [7,8]],
                     [[9,10],
                      [11,12]]])
print(x.size())

torch.Size([3, 2, 2])


In [ ]:
#텐서의 0번차원의 0번 인덱스 슬라이싱
print(x[0])

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
#텐서의 0번 차원의 마지막 인덱스 슬라이싱
print(x[-1])

tensor([[ 9., 10.],
        [11., 12.]])


In [ ]:
#텐서의 1번차원의 0번 인덱스 슬라이싱
print(x[:,0])

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])


In [ ]:
#궁금증1: 다음 슬라이싱의 결과는?
print(x[1:2,1:,:].size())

torch.Size([1, 1, 2])


# 파이토치 텐서 자르기: split함수

In [ ]:
#split함수: 지정한 차원이 원하는 크기가 되도록 등분함
x=torch.FloatTensor(10,4)
splits=x.split(4,dim=0)
for s in splits:
    print(s.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


파이토치 텐서 자르기: chunk함수

In [ ]:
#chunk함수: 지정된 개수로 텐서를 나눔
x=torch.FloatTensor(8,4)
chunks=x.chunk(3,dim=0)

for c in chunks:
        print(c.size())

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


# 파이토치 텐서 자르기: index_select함수

In [ ]:
#3x2x2크기의 파이토치 텐서 생성
#숫자 2와 1을 포함하는 1차원 정수형 텐서 생성
x=torch.FloatTensor([[[1,1],
                     [2,2]],
                    [[3,3],
                     [4,4]],
                    [[5,5],
                     [6,6]]])
indice=torch.LongTensor([2,1])
print(x.size())

torch.Size([3, 2, 2])


In [ ]:
#index_select함수: 원하는 인덱스의 값만을 추출
y=x.index_select(dim=0,index=indice)
print(y)
print(y.size())

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [ ]:
#궁금증2: 무슨일이 벌어진 걸까?
indice=torch.LongTensor([2,1])
y=x.index_select(dim=0,index=indice)
print(y)
print(y.size())

파이토치 텐서 붙이기: CAT함수

In [ ]:
#크기가 각각 3x3인 두개의 파이토치 텐서 생성
x=torch.FloatTensor([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
y=torch.FloatTensor([[10,11,12],
                     [13,14,15],
                     [16,17,18]])
print(x.size(),y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [ ]:
#cat함수: 지정한 차원으로 텐서 붙이기
z=torch.cat([x,y],dim=0)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])


In [ ]:
#0번차원으로 3x3크기의 두 텐서를 붙임(위아래)
#차원을 -1로 지정함으로써 마지막 차원으로 두 텐서 붙이기
z=torch.cat([x,y],dim=-1)
print(z)
print(z.size())

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


붙이고자 하는 차원이외의 차원의 크기가 서로 맞지 않으면 붙일 수 없음

예) 1번 차원으로 두 2d 텐서를 붙이려 할 때, 나머지 차원의 크기가 다른 경우

# 파이토치 텐서 붙이기: stack함수

In [ ]:
#크기가 각각 3x3인 두 개의 파이토치 텐서 생성
x=torch.FloatTensor([[1,2,3,],
                     [4,5,6],
                     [7,8,9]])
y=torch.FloatTensor([[10,11,12],
                     [13,14,15],
                     [16,17,18]])
print(x.size(),y.size())

torch.Size([3, 3]) torch.Size([3, 3])


In [ ]:
#stack함수: 텐서를 쌓아 더 높은 차원의 텐서를 생성
z=torch.stack([x,y])
print(z)
print(z.size())

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])


In [ ]:
#쌓고자 하는 차원을 지정할 수 있음
z=torch.stack([x,y],dim=-1)
print(z)
print(z.size())

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]],

        [[ 7., 16.],
         [ 8., 17.],
         [ 9., 18.]]])
torch.Size([3, 3, 2])


#연습문제#
###연습문제1 궁금증1을 해결하시오
###문제2 궁금증2를 해결하시오
###문제3 unsqueeze, cat함수를 이용하여 다음 stack함수와 같은 결과가 나오도록 빈칸을 채우시오
d=0

z=torch.stack([x,y],dim=d)

----------빈칸--------------  

print(z)

    tensor([[[1.,2.,3.],
            [4.,5.,6.],
            [7.,8.,9.]],

            [[10.,11.,12.],
            [13.,14.,15.],
            [16.,17.,18.]]])
print(z.size())

    torch.size([2,3,3])
###문제4 다음 코드의 실행이 완료되었을 때 텐서 result의 크기는 무엇인가?
    result=[]
    for i in range(5):
        x=torch.FloatTensor(2,2)
        result += [x]
    result=torch.stack(result)

###문제5 크기가 3x3x3인 임의의 수들로 이루어진 두 개의 텐서를 쌓아 2x3x3x3크기의 텐서를 생성하는 프로그램을 작성하시오.

###문제5에서 생성한 4차원 텐서를 다시 두개의 3차원 텐서로 분리하는 코드를 작성하시오
