<a href="https://colab.research.google.com/github/chaehchaeh/MajorAI-DL/blob/main/dl1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###딥러닝이란?
    #심층신경망(DNN)을 학습시켜 인공지능을 갖도록 한 뒤 이를 이용해 문제를 해결하는 것으로 머신러닝의 일종
    #수학적으로 y=f(x)처럼 X가 입력으로 주어졌을 때 Y를 반환하는 함수로 간주할 수 있음
    # f가 특정한 방식으로 동작하도록 데이터를 이용해 파라미터를 학습시킴
###머신러닝VS딥러닝?
    #ML: input->feature extraction(인간)->classification(컴퓨터)->Output
    #DL: input-> 특성추출과 분류(컴퓨터)->출력/ 정보를 저니달하는 신경망을 사용하여 데이터의 특징 및 관계를 해석한다
###머신러닝 학습의 종류
    #지도학습(supervised Learning): classification/regression
    #비지도학습:clustering/dimensionality reduction
    #강화학습(reinforcement learning): agent 변화하는 환경에 따라 행동을 취하면서 보상을 얻게되며, 보상이 큰 행동을 더 자주하도록 학습진행
###딥러닝 학습의 종류
    #지도학습: 이미지분류/시계열 데이터 분석
    #비지도학습: 군집/차원축소
    #전이학습(transfer learning): 전이학습
    #강화학습


In [ ]:
#파이토치의 기본단위:tensor
#파이토치 불러오기
import torch
#임의의 값으로 채워진 원하는 크기의 텐서 생성
x=torch.FloatTensor(3,2)
x

tensor([[3.5839e-35, 0.0000e+00],
        [3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])

In [ ]:
#long타입과 Byte타입 텐서 생성
lt=torch.LongTensor([[1,2],
                     [3,4]])
bt=torch.ByteTensor([[1,0],
                     [0,1]])

#텐서의 타입변환
ft.long()
tensor([[1,2],
        [3,4]])
lt.float()
tensor([[1.,2.],
        [3.,4.]])

NameError: ignored

In [ ]:
#넘파이 배열 생성
import numpy as np
x=np.array([[1,2],
            [3,4]])#define numpy array
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
#넘파이 배열을 파이토치 텐서로 변환
x=torch.from_numpy(x)
print(x,type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [ ]:
#파이토치 텐서를 넘파이 배열로 변환
x=x.numpy()
print(x,type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
#텐서의 크기구하기
x=torch.FloatTensor([[[1,2],
                     [3,4]],
                     [[5,6],
                     [7,8]],
                    [[9,10],
                     [11,12]]])
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [ ]:
#텐서의 특정차원의 크기 접근
print(x.size(1))
print(x.shape[1])
print(x.size(-1))
print(x.shape[-1])

2
2
2
2


In [ ]:
#텐서 차원의 갯수
print(x.dim())
print(len(x.size()))

3
3


In [ ]:
#텐서의 덧셈
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])
print(a+b)

tensor([[3., 4.],
        [6., 7.]])


In [ ]:
#텐서의 뺄셈, 곱셈, 나눗셈
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])
print(a-b)#뺄셈
print(a*b)#곱셈
print(a/b)#나눗셈

tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])


In [ ]:
#텐서의 거듭제곱
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])
print(a**b)

tensor([[ 1.,  4.],
        [27., 64.]])


In [ ]:
#텐서의 논리연산
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])
print(a==b)
print(a!=b)

tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])


In [ ]:
#텐서의 인플레이스 연산: 기존의 텐서가 연산결과로 대체됨
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])
print("기존연산")
print(a.mul(b))
print(a)
print()
print("인플레이스 연산")
print(a.mul_(b))
print(a)

기존연산
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])

인플레이스 연산
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


In [ ]:
x=torch.FloatTensor([[1,2],[3,4]])
print("텐서 요소의 전체 합과 평균")
print(x.sum())
print(x.mean())
print()
print("텐서 세로축(dim=0)에 대해 합 연산")
print(x.sum(dim=0))
print()
print("텐서 마지막 차원(dim=-1)에 대해 합 연산")
print(x.sum(dim=-1))

텐서 요소의 전체 합과 평균
tensor(10.)
tensor(2.5000)

텐서 세로축(dim=0)에 대해 합 연산
tensor([4., 6.])

텐서 마지막 차원(dim=-1)에 대해 합 연산
tensor([3., 7.])


In [ ]:
#브로드 캐스트 연산:텐서+스칼라
x=torch.FloatTensor([[1,2],[3,4]])
y=1
z=x+y
print(z)
print(z.size())

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [ ]:
#브로드 캐스트 연산:텐서(2d)+벡터
x=torch.FloatTensor([[1,2],[4,8]])
y=torch.FloatTensor([3,5])
print(x.size())
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([2, 2])
torch.Size([2])
tensor([[ 4.,  7.],
        [ 7., 13.]])
torch.Size([2, 2])


In [ ]:
#브로드 캐스트 연산:텐서(3D)+벡터
x=torch.FloatTensor([[[1,2]]])
y=torch.FloatTensor([3,5])
print(x.size())
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([1, 1, 2])
torch.Size([2])
tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


In [ ]:
#브로드캐스트 연산:텐서(2d)+텐서(2d)
x=torch.FloatTensor([[1,2]])
y=torch.FloatTensor([[3],[5]])
print(x.size())
print(y.size())
z=x+y
print(z)
print(z.size())

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


In [ ]:
#####연습문제####
#다음과 같은 텐서가 주어졌을 때,
x=torch.FloatTensor([[[1,2],
                     [3,4]],
                     [[5,6],
                      [7,8]],
                     [[9,10],
                      [11,12]]])
#1
print("텐서요소들의 합과 평균을 구하는 프로그램을 작성하시오")
print(x.sum())#합
print(x.mean())#평균
#2
print("텐서의 첫번째 차원에 대한 합과 평균을 구하는 프로그램을 작성하시오")
print(x.sum(dim=0))
print(x.mean(dim=0))
#3
print("텐서의 마지막 차원에 대한 합과 평균을 구하는 프로그램을 작성하시오")
print(x.sum(dim=-1))
print(x.mean(dim=-1))

텐서요소들의 합과 평균을 구하는 프로그램을 작성하시오
tensor(78.)
tensor(6.5000)
텐서의 첫번째 차원에 대한 합과 평균을 구하는 프로그램을 작성하시오
tensor([[15., 18.],
        [21., 24.]])
tensor([[5., 6.],
        [7., 8.]])
텐서의 마지막 차원에 대한 합과 평균을 구하는 프로그램을 작성하시오
tensor([[ 3.,  7.],
        [11., 15.],
        [19., 23.]])
tensor([[ 1.5000,  3.5000],
        [ 5.5000,  7.5000],
        [ 9.5000, 11.5000]])
