<a href="https://colab.research.google.com/github/chaehchaeh/MajorAI-DL/blob/main/DL%EA%B3%BC%EC%A0%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
X=torch.FloatTensor([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
Y=torch.FloatTensor([[3,3,3],[5,5,5]])
Z=X+Y
print(Z)

tensor([[[ 4.,  5.,  6.],
         [ 9., 10., 11.]],

        [[14., 25., 36.],
         [49., 60., 71.]]])


In [ ]:
#문제2
X=torch.FloatTensor([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
#모든 요소의 평균과 합을 구하는 코드를 작성하시오.
print(X.sum())
print(X.mean())
#첫번째 차원에 대한 평균과 합을 구하는 코드를 작성하시오.
print(X.sum(dim=0))
print(X.mean(dim=0))
#두번째 차원에 대한 평균과 합을 구하는 코드를 작성하시오.
print(X.sum(dim=1))
print(X.mean(dim=1))

tensor(252.)
tensor(21.)
tensor([[12., 24., 36.],
        [48., 60., 72.]])
tensor([[ 6., 12., 18.],
        [24., 30., 36.]])
tensor([[ 5.,  7.,  9.],
        [55., 77., 99.]])
tensor([[ 2.5000,  3.5000,  4.5000],
        [27.5000, 38.5000, 49.5000]])


In [ ]:
#문제3
X=torch.FloatTensor([1,2,3])
Y=X.expand(1,1,3)
print(Y.size())

torch.Size([1, 1, 3])


In [ ]:
#문제4
import torch
X=torch.FloatTensor(range(12))
X=X.view(2,3,2)
print(X)

tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]]])


In [20]:
#문제5
import torch
X=torch.FloatTensor([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
X=X.chunk(6,dim=2)
for x in X:
    print(x)

tensor([[[ 1.],
         [ 4.]],

        [[11.],
         [44.]]])
tensor([[[ 2.],
         [ 5.]],

        [[22.],
         [55.]]])
tensor([[[ 3.],
         [ 6.]],

        [[33.],
         [66.]]])


In [27]:
#문제5
import torch
X=torch.FloatTensor([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
X=X.chunk(3,dim=-1)
for x in X:
    print(x)

tensor([[[ 1.],
         [ 4.]],

        [[11.],
         [44.]]])
tensor([[[ 2.],
         [ 5.]],

        [[22.],
         [55.]]])
tensor([[[ 3.],
         [ 6.]],

        [[33.],
         [66.]]])


In [38]:
#문제6
X=torch.FloatTensor([ [[[1,2,3],[4,5,6]], [[2,4,6],[3,5,7]]],
                      [[[1,1,1],[2,2,2]], [[3,3,3],[4,4,4]]]  ])
Y=torch.FloatTensor([ [[[1,1],[2,2],[3,3]], [[1,1],[1,1],[1,1]]],
                    [[[2,2],[3,3],[4,4]], [[1,2],[1,2],[1,2]]]  ])
X1=X.size()
Y1=Y.size()
Z1=Z.size()
Z=torch.matmul(X,Y)
print(Z)

tensor([[[[14., 14.],
          [32., 32.]],

         [[12., 12.],
          [15., 15.]]],


        [[[ 9.,  9.],
          [18., 18.]],

         [[ 9., 18.],
          [12., 24.]]]])
